### ISSUE TITLE
Fails to load or ignore `.node` files in node.js build

### ISSUE THREAD

**Issue by kevzettler** [andywer/threads-plugin#29]
Continuation of https://github.com/andywer/threads-plugin/issues/25 I'm seeing failures from webpack trying to load binary modules or `.node` files.  The code i'm importing in `server.worker.ts` builds successfully with the same webpack config when I don't use it as a worker. Seems as if the threads-plugin is not respecting the other webpack exclusions or loaders.

```
ERROR in ./server.worker.ts (../node_modules/threads-plugin/dist/loader.js?{"name":"0"}!./server.worker.ts)
Module build failed (from ../node_modules/threads-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/kevzettler/code/hypeworks/node_modules/webpack/lib/NormalModule.js:469:19)
    at /Users/kevzettler/code/hypeworks/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/kevzettler/code/hypeworks/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/kevzettler/code/hypeworks/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/kevzettler/code/hypeworks/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/kevzettler/code/hypeworks/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/kevzettler/code/hypeworks/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/kevzettler/code/hypeworks/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/kevzettler/code/hypeworks/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
 @ ./server.ts 1:0-119
Child WorkerPluginLoader:
                     Asset     Size  Chunks                   Chunk Names
        0.server.worker.js  4.1 MiB       0  [emitted]        0
    0.server.worker.js.map  3.9 MiB       0  [emitted] [dev]  0
    Entrypoint 0 = 0.server.worker.js 0.server.worker.js.map
    [../node_modules/ts-loader/index.js?!./server.worker.ts] ../node_modules/ts-loader??ref--4!./server.worker.ts 11.4 KiB {0} [built]
    [./AIPlayer.ts] 1.92 KiB {0} [built]
    [./Animate.ts] 7.86 KiB {0} [built]
    [./AssetDependency.ts] 5.04 KiB {0} [built]
    [./AssetStore.ts] 6.9 KiB {0} [built]
    [./AttackAnimations.ts] 2.14 KiB {0} [built]
    [./BroadPhaseBox.ts] 7.31 KiB {0} [built]
    [./CollisionHull.ts] 3.59 KiB {0} [built]
    [./EllipsoidGeometry.ts] 2.02 KiB {0} [built]
    [./EllipsoidTriCollide.ts] 6.59 KiB {0} [built]
    [./EntityStore.ts] 9.78 KiB {0} [built]
    [./RootStore.ts] 4.12 KiB {0} [built]
    [./addPlayerEntity.ts] 5.68 KiB {0} [built]
    [./network/ServerNetwork.ts] 5 KiB {0} [built]
    [./scene.ts] 6.99 KiB {0} [built]
        + 588 hidden modules

    WARNING in ../node_modules/socket.io/lib/index.js 113:11-32
    Critical dependency: the request of a dependency is an expression
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

    WARNING in ../node_modules/engine.io/lib/server.js 106:58-80
    Critical dependency: the request of a dependency is an expression
     @ ../node_modules/engine.io/lib/engine.io.js
     @ ../node_modules/socket.io/lib/index.js
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

    WARNING in ../node_modules/wrtc/lib/binding.js
    Module not found: Error: Can't resolve '../build/Debug/wrtc.node' in '/Users/kevzettler/code/hypeworks/node_modules/wrtc/lib'
     @ ../node_modules/wrtc/lib/binding.js
     @ ../node_modules/wrtc/lib/index.js
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

    WARNING in ../node_modules/engine.io-client/node_modules/ws/lib/buffer-util.js
    Module not found: Error: Can't resolve 'bufferutil' in '/Users/kevzettler/code/hypeworks/node_modules/engine.io-client/node_modules/ws/lib'
     @ ../node_modules/engine.io-client/node_modules/ws/lib/buffer-util.js
     @ ../node_modules/engine.io-client/node_modules/ws/lib/receiver.js
     @ ../node_modules/engine.io-client/node_modules/ws/index.js
     @ ../node_modules/engine.io-client/lib/transports/websocket.js
     @ ../node_modules/engine.io-client/lib/transports/index.js
     @ ../node_modules/engine.io-client/lib/socket.js
     @ ../node_modules/engine.io-client/lib/index.js
     @ ../node_modules/socket.io-client/lib/manager.js
     @ ../node_modules/socket.io-client/lib/index.js
     @ ./network/NetworkBase.ts
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

    WARNING in ../node_modules/engine.io/node_modules/ws/lib/buffer-util.js
    Module not found: Error: Can't resolve 'bufferutil' in '/Users/kevzettler/code/hypeworks/node_modules/engine.io/node_modules/ws/lib'
     @ ../node_modules/engine.io/node_modules/ws/lib/buffer-util.js
     @ ../node_modules/engine.io/node_modules/ws/lib/receiver.js
     @ ../node_modules/engine.io/node_modules/ws/index.js
     @ ../node_modules/engine.io/lib/server.js
     @ ../node_modules/engine.io/lib/engine.io.js
     @ ../node_modules/socket.io/lib/index.js
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

    WARNING in ../node_modules/engine.io-client/node_modules/ws/lib/validation.js
    Module not found: Error: Can't resolve 'utf-8-validate' in '/Users/kevzettler/code/hypeworks/node_modules/engine.io-client/node_modules/ws/lib'
     @ ../node_modules/engine.io-client/node_modules/ws/lib/validation.js
     @ ../node_modules/engine.io-client/node_modules/ws/lib/receiver.js
     @ ../node_modules/engine.io-client/node_modules/ws/index.js
     @ ../node_modules/engine.io-client/lib/transports/websocket.js
     @ ../node_modules/engine.io-client/lib/transports/index.js
     @ ../node_modules/engine.io-client/lib/socket.js
     @ ../node_modules/engine.io-client/lib/index.js
     @ ../node_modules/socket.io-client/lib/manager.js
     @ ../node_modules/socket.io-client/lib/index.js
     @ ./network/NetworkBase.ts
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

    WARNING in ../node_modules/engine.io/node_modules/ws/lib/validation.js
    Module not found: Error: Can't resolve 'utf-8-validate' in '/Users/kevzettler/code/hypeworks/node_modules/engine.io/node_modules/ws/lib'
     @ ../node_modules/engine.io/node_modules/ws/lib/validation.js
     @ ../node_modules/engine.io/node_modules/ws/lib/receiver.js
     @ ../node_modules/engine.io/node_modules/ws/index.js
     @ ../node_modules/engine.io/lib/server.js
     @ ../node_modules/engine.io/lib/engine.io.js
     @ ../node_modules/socket.io/lib/index.js
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

    ERROR in ../node_modules/wrtc/build/Release/wrtc.node 1:0
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    (Source code omitted for this binary file)
     @ ../node_modules/wrtc/lib/binding.js 6:19-56
     @ ../node_modules/wrtc/lib/index.js
     @ ./network/ServerNetwork.ts
     @ ../node_modules/ts-loader??ref--4!./server.worker.ts

```

**Comment by kevzettler** [comment]
If I move the wrtc module out of the `server.worker.ts` worker file and in to the 'main thread' file of server.ts I can get it to compile.

**Comment by andywer** [comment]
Yeah, that damn webpack child compiler once more…

You could try to monkey-patch a fix here and see if it works: https://github.com/andywer/threads-plugin/blob/master/src/loader.js#L42

Add `loaders` to `workerOptions`, set it to `compilerOptions.loaders`. Don't forget to edit the file in `lib/`.
If that solves it, we can open a PR and release the fix.
